name: Deploy to Google Cloud Functions

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/deploy-cloud-functions@v0.9.0
      with:
        name: ai-function
        runtime: python39
        entry_point: generate_response
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_SA_KEY }}